require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DivsController do

  # This should return the minimal set of attributes required to create a valid
  # Div. As you add validations to Div, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DivsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all divs as @divs" do
      div = Div.create! valid_attributes
      get :index, {}, valid_session
      assigns(:divs).should eq([div])
    end
  end

  describe "GET show" do
    it "assigns the requested div as @div" do
      div = Div.create! valid_attributes
      get :show, {:id => div.to_param}, valid_session
      assigns(:div).should eq(div)
    end
  end

  describe "GET new" do
    it "assigns a new div as @div" do
      get :new, {}, valid_session
      assigns(:div).should be_a_new(Div)
    end
  end

  describe "GET edit" do
    it "assigns the requested div as @div" do
      div = Div.create! valid_attributes
      get :edit, {:id => div.to_param}, valid_session
      assigns(:div).should eq(div)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Div" do
        expect {
          post :create, {:div => valid_attributes}, valid_session
        }.to change(Div, :count).by(1)
      end

      it "assigns a newly created div as @div" do
        post :create, {:div => valid_attributes}, valid_session
        assigns(:div).should be_a(Div)
        assigns(:div).should be_persisted
      end

      it "redirects to the created div" do
        post :create, {:div => valid_attributes}, valid_session
        response.should redirect_to(Div.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved div as @div" do
        # Trigger the behavior that occurs when invalid params are submitted
        Div.any_instance.stub(:save).and_return(false)
        post :create, {:div => {  }}, valid_session
        assigns(:div).should be_a_new(Div)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Div.any_instance.stub(:save).and_return(false)
        post :create, {:div => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested div" do
        div = Div.create! valid_attributes
        # Assuming there are no other divs in the database, this
        # specifies that the Div created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Div.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => div.to_param, :div => { "these" => "params" }}, valid_session
      end

      it "assigns the requested div as @div" do
        div = Div.create! valid_attributes
        put :update, {:id => div.to_param, :div => valid_attributes}, valid_session
        assigns(:div).should eq(div)
      end

      it "redirects to the div" do
        div = Div.create! valid_attributes
        put :update, {:id => div.to_param, :div => valid_attributes}, valid_session
        response.should redirect_to(div)
      end
    end

    describe "with invalid params" do
      it "assigns the div as @div" do
        div = Div.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Div.any_instance.stub(:save).and_return(false)
        put :update, {:id => div.to_param, :div => {  }}, valid_session
        assigns(:div).should eq(div)
      end

      it "re-renders the 'edit' template" do
        div = Div.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Div.any_instance.stub(:save).and_return(false)
        put :update, {:id => div.to_param, :div => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested div" do
      div = Div.create! valid_attributes
      expect {
        delete :destroy, {:id => div.to_param}, valid_session
      }.to change(Div, :count).by(-1)
    end

    it "redirects to the divs list" do
      div = Div.create! valid_attributes
      delete :destroy, {:id => div.to_param}, valid_session
      response.should redirect_to(divs_url)
    end
  end

end
